// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriangleLogoDrawer.Infrastructure.Data;

namespace TriangleLogoDrawer.Infrastructure.Migrations
{
    [DbContext(typeof(TriangleDrawerDbContext))]
    partial class TriangleDrawerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BackgroundImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Order", b =>
                {
                    b.Property<int>("ShapeId")
                        .HasColumnType("int");

                    b.Property<int>("TriangleId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TriangleId1")
                        .HasColumnType("int");

                    b.HasKey("ShapeId", "TriangleId");

                    b.HasIndex("TriangleId")
                        .IsUnique();

                    b.HasIndex("TriangleId1")
                        .IsUnique()
                        .HasFilter("[TriangleId1] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Triangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int?>("PointId")
                        .HasColumnType("int");

                    b.Property<int>("PointOneId")
                        .HasColumnType("int");

                    b.Property<int>("PointThreeId")
                        .HasColumnType("int");

                    b.Property<int>("PointTwoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("PointId");

                    b.HasIndex("PointOneId");

                    b.HasIndex("PointThreeId");

                    b.HasIndex("PointTwoId");

                    b.ToTable("Triangles");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Order", b =>
                {
                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Shape", "Shape")
                        .WithMany("Orders")
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Triangle", "Triangle")
                        .WithOne()
                        .HasForeignKey("TriangleLogoDrawer.ApplicationCore.Entities.Order", "TriangleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Triangle", null)
                        .WithOne("order")
                        .HasForeignKey("TriangleLogoDrawer.ApplicationCore.Entities.Order", "TriangleId1");

                    b.Navigation("Shape");

                    b.Navigation("Triangle");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Point", b =>
                {
                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Image", "Image")
                        .WithMany("Points")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Shape", b =>
                {
                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Image", "Image")
                        .WithMany("Shapes")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Triangle", b =>
                {
                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Image", "Image")
                        .WithMany("Triangles")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Point", null)
                        .WithMany("Triangles")
                        .HasForeignKey("PointId");

                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Point", "PointOne")
                        .WithMany("TrianglesPointOne")
                        .HasForeignKey("PointOneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Point", "PointThree")
                        .WithMany("TrianglesPointThree")
                        .HasForeignKey("PointThreeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TriangleLogoDrawer.ApplicationCore.Entities.Point", "PointTwo")
                        .WithMany("TrianglesPointTwo")
                        .HasForeignKey("PointTwoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("PointOne");

                    b.Navigation("PointThree");

                    b.Navigation("PointTwo");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Image", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Shapes");

                    b.Navigation("Triangles");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Point", b =>
                {
                    b.Navigation("Triangles");

                    b.Navigation("TrianglesPointOne");

                    b.Navigation("TrianglesPointThree");

                    b.Navigation("TrianglesPointTwo");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Shape", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TriangleLogoDrawer.ApplicationCore.Entities.Triangle", b =>
                {
                    b.Navigation("order");
                });
#pragma warning restore 612, 618
        }
    }
}
